name = "php-library"
title = "PHP Library Manual"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv"
              ]

# toc_landing_pages = ["/paths/to/pages/that/have/nested/content"]

[substitutions]
php-library = "MongoDB PHP Library"

